name: Run tests

on: [pull_request]

jobs:
  build-and-launch:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.8"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
    
      - name: Run compstrat tests
        working-directory: compstrat
        run: |
          python3 -m pytest tests -sv
